default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: thoughtbox-assessment_development

test:
  <<: *default
  database: thoughtbox-assessment_test

production:
  <<: *default
  database: thoughtbox-assessment_production
  username: thoughtbox-assessment
  password: <%= ENV['THOUGHTBOX-ASSESSMENT_DATABASE_PASSWORD'] %>
